### ISSUE TITLE
/application/{id} contains incomplete `review` data

### ISSUE THREAD

**Issue by carlosthe19916** [konveyor/tackle-application-inventory#50]
- Create an application `POST /application`
- Create a review for the application previously created `POST /review` . The body should have fields like `proposedAction`, `effortEstimate`, `businessCriticality`, etc.
- Get the application created in the first step `GET /application/{applicationId}` and you will see something the example below. Pay attention to the field `review`, the only field it has is the `id` but the field `review` should have all data associated to the review like `proposedAction`, `effortEstimate`, `businessCriticality`, etc.

```json
{
   "id":4,
   "createUser":"admin",
   "updateUser":"admin",
   "name":"app2",
   "description":"",
   "businessService":null,
   "comments":"",
   "tags":[],
   "review":{
      "id":5
   }
}
```

I'm also attaching a video to give more context about the issue:

https://user-images.githubusercontent.com/2582866/117136207-59584480-ada8-11eb-9dad-a80e74810d6a.mp4

**Comment by mrizzi** [comment]
Providing only the review's `id` has been done on purpose considering having all the review's data for the application entity was useless.
I would suggest to use the appropriate `/review` endpoint for creating the Review page rather than the `/application` one which is not meant for managing the `review` entity (considering the Review page should also save the review).
Further details in the [`review` endpoint](https://github.com/konveyor/tackle-application-inventory/blob/main/USAGE.md#review-endpoint) usage guide.

I will keep this open as long as https://github.com/konveyor/tackle-ui/issues/105 is not completed in case something else will be found.

**Comment by mrizzi** [comment]
https://github.com/konveyor/tackle-ui/issues/105 has been closed, so I'm going to close this as well as agreed.
